env:
  node: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
rules:
  no-console: off
  import/export: off
  no-plusplus: off
  no-constant-condition: off
  import/extensions: ["error", "ignorePackages", { "js": "always" }]